apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara9280-dara-tan-test-react-again-certificate
  namespace: tan-dara9280-dara-tan-test-react-again
spec:
  secretName: tan-dara9280-dara-tan-test-react-again-secret-tls
  commonName: tan-dara9280-dara-tan-test-react-again.assessify.org
  dnsNames:
  - tan-dara9280-dara-tan-test-react-again.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
